services:
  - type: web
    name: color-fix-match
    env: python
    plan: free
    region: frankfurt
    branch: main
    rootDir: color-fix-match

    buildCommand: pip install -r requirements.txt

    startCommand: python server.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3

    autoDeploy: true